version: 2.1

orbs:
  kitchen: sous-chefs/kitchen@1.0.2

workflows:
  kitchen:
    jobs:
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/delivery:
          name: delivery
      - kitchen/dokken-single:
          name: default-debian-8
          suite: default
          platform: debian-8
          requires: [  danger, delivery ]
      - kitchen/dokken-single:
          name: default-debian-9
          suite: default
          platform: debian-9
          requires: [  danger, delivery ]
      - kitchen/dokken-single:
          name: default-centos-6
          suite: default
          platform: centos-6
          requires: [  danger, delivery ]
      - kitchen/dokken-single:
          name: default-centos-7
          suite: default
          platform: centos-7
          requires: [  danger, delivery ]
      - kitchen/dokken-single:
          name: default-ubuntu-1604
          suite: default
          platform: ubuntu-1604
          requires: [  danger, delivery ]
      - kitchen/dokken-single:
          name: default-ubuntu-1804
          suite: default
          platform: ubuntu-1804
          requires: [  danger, delivery ]
