version: 2.1

orbs:
  kitchen: sous-chefs/kitchen@1.0.2

workflows:
  kitchen:
    jobs:
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/delivery:
          name: delivery
      - kitchen/dokken:
          name: default
          suite: default
          requires: [  danger, delivery ]
